
# common application properties:
app:
  server:
    hostname: http://localhost:2024
  mail:
    from: secret_santa_no_reply@e-soft.ru # от кого отправляется почта
    text-templates:
      subject: "Тайный дед мороз (%s)"
      good-morning: "Отличного утра и прекрасного настроения!"
      good-day: "Хорошего дня и прекрасного настроения!"
      good-evening: "Замечательного вечера и прекрасного настроения!"
      good-night: "Доброй ночи и прекрасного настроения!"
      draw-results: "Получены результаты жеребьевки!%nВаш подопечный, которому нужно подготовить подарок:%n%n- %s %s%s %n%nПоложить Ваш подарок можно будет под елку, которая установлена в Вашем подразделении. Главное, сделать это нужно до 27 декабря и на упаковке подарка ОБЯЗАТЕЛЬНО указать получателя!%n%s"
      draw-cancel: "Результаты жеребьевки сброшены.%nПри повторной жеребьевке вам будет отправлено сообщение с новыми результатами.%n%s"
      participant-credits: "Поздравляем! Вы успешно зарегистрированы и участвуете в игре Тайный Дед Мороз! (%s)%nВаши учетные данные:%nЛогин: %s%nПароль: %s%nБолее подробную информацию можно посмотреть на сайте.%n%n%s"
      participant-draw-changes: "Произошли изменения в жеребьевке, вам назначен другой подопечный:%n%s : %s%s%n%n%s"
      participant-deleted: "Очень жаль, что Вы отказались от участия в игре Тайный Дед Мороз! %s%n%n%s"
      participant-2g2-cared: "Ваш подопечный был передан в надежные руки."
      participant-2g2-info: " (пожелания к подарку: %s)"
      success-registration: "Вы успешно зарегистрированы! Вам придет письмо с данными для входа"
      password-resent: "Пароль был отправлен по почте"
      not-registered: "Данный пользователь не зарегистрирован!"
      too-many-registration-attempts: "Вы уже зарегистрированы"
      wrong-group: "некорректно выбрано подразделение"
      use-specific-email: "Используйте ваш корпоративный адрес в домене @my-office.org"
spring:
  # mail properties:
  mail:
    protocol: smtps
    host: mail.my-office.org
    port: 465
    username: user@my-office.org
    password: pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2

  # DB properties:
  datasource:
    url: jdbc:h2:file:${user.home}/secret_santa/${spring.datasource.db-name:db}
    username: admin
    password: admin
    driverClassName: org.h2.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 20
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      continue-on-error: true
      encoding: UTF-8
  h2:
    console:
      enabled: false
